#!/usr/bin/env php
<?php

/** @var DI\Container $container */
$container = require __DIR__ . '/bootstrap.php';

$container->get('slackClient')
    ->connect()
    ->then([$container->get(P4l\Pikabot\Client::class), 'onConnect']);

$container->get('eventLoop')->run();
